services:
  db:
    image: postgres
    container_name: benew-db
    environment:
      POSTGRES_USER: someUser
      POSTGRES_PASSWORD: somePass
      POSTGRES_DB: benew_test
    restart: always
    ports:
      - "5432:5432"