services:
  db:
    image: postgres
    container_name: benew-db
    environment:
      POSTGRES_USER: someUser
      POSTGRES_PASSWORD: somePass
      POSTGRES_DB: benew_test
    restart: always
    ports:
      - "5432:5432"
  # app:
  #   build: .
  #   container_name: olxsearch-app
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test_db
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db