--liquibase formatted sql

--changeset benew:20251103100001_create_app_user_table
--comment: Create app_user table for storing all system users

/*
 * Migration: Create app_user Table
 * Purpose: Create central table for storing all users (Admin, Manager, User)
 * Author: Database Architect
 * Date: 2025-11-03
 * 
 * This migration creates the app_user table which:
 * - Stores all user types in a single table (ADMIN, MANAGER, USER)
 * - Implements self-referencing relationship for manager-employee hierarchy
 * - Uses UUID as primary key (generated by Spring Boot application)
 * - Includes audit columns (created_at, updated_at) managed by Spring Data JPA
 * 
 * Key Design Decisions:
 * - UUID primary keys generated by application (@GeneratedValue(strategy = GenerationType.UUID))
 * - No database-level ENUM for role - validation happens in Spring application
 * - Unique constraint on email for authentication
 * - manager_id is optional (NULL for Admins and top-level Managers)
 * - position_name is optional (NULL for Admins who don't have onboarding processes)
 * 
 * Tables Created: benew.app_user
 * Dependencies: benew schema (from migration 20251103100000)
 * 
 * Special Notes:
 * - Self-referencing foreign key uses ON DELETE RESTRICT to prevent accidental deletion
 *   of managers who have employees assigned
 * - Email uniqueness is enforced via constraint, case-insensitive uniqueness 
 *   via separate index (in later migration)
 */

-- create app_user table
-- this table stores all users in the system with three distinct roles
create table benew.app_user (
    -- primary key: uuid generated by spring boot application
    id uuid primary key,
    
    -- authentication fields
    -- email is used as username for login
    -- must be unique across all users
    email varchar(255) not null,
    
    -- bcrypt password hash stored by spring security
    -- actual password is never stored in plain text
    password_hash varchar(255) not null,
    
    -- user role: ADMIN, MANAGER, or USER
    -- validated at application level via java enum
    -- no database enum type used per architectural decision
    role varchar(50) not null,
    
    -- personal information
    -- required for all users
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    
    -- position/job title
    -- used to assign appropriate onboarding template
    -- null for administrators who don't undergo onboarding
    position_name varchar(50),
    
    -- self-referencing foreign key for manager-employee relationship
    -- null for administrators and top-level managers
    -- references the manager (another user in this same table)
    manager_id uuid,
    
    -- audit columns managed by spring data jpa auditing
    -- @CreatedDate and @LastModifiedDate annotations
    -- timestamps stored with timezone information
    created_at timestamptz not null,
    updated_at timestamptz not null,
    
    -- self-referencing foreign key constraint
    -- on delete restrict prevents deletion of managers with assigned employees
    -- application logic must reassign employees before manager deletion
    constraint fk_app_user_manager 
        foreign key (manager_id) 
        references benew.app_user(id) 
        on delete restrict,
    
    -- unique constraint on email for authentication
    -- additional case-insensitive unique index will be created in later migration
    constraint uk_app_user_email 
        unique (email)
);

-- table comment explaining purpose and usage
comment on table benew.app_user is 
    'Central user table storing all system users with three roles: ADMIN, MANAGER, USER. Implements self-referencing manager-employee hierarchy via manager_id.';

-- column comments for documentation
comment on column benew.app_user.id is 
    'Primary key (UUID). Generated by Spring Boot using @GeneratedValue(strategy = GenerationType.UUID).';

comment on column benew.app_user.email is 
    'User email address. Used as username for authentication. Must be unique (case-insensitive check via index).';

comment on column benew.app_user.password_hash is 
    'BCrypt password hash. Never store plain text passwords. Managed by Spring Security.';

comment on column benew.app_user.role is 
    'User role: ADMIN, MANAGER, or USER. Validated in Spring application via @Enumerated(EnumType.STRING). No database-level CHECK constraint per architectural decision.';

comment on column benew.app_user.first_name is 
    'User first name. Required for all users.';

comment on column benew.app_user.last_name is 
    'User last name. Required for all users. Indexed for search performance.';

comment on column benew.app_user.position_name is 
    'Job title/position. Used to assign appropriate onboarding template when creating new employee. NULL for administrators. Application normalizes value (trim + toLowerCase) before save/search.';

comment on column benew.app_user.manager_id is 
    'Self-referencing foreign key to manager (another user in this table). NULL for administrators and top-level managers without supervisors. ON DELETE RESTRICT prevents deletion of managers with assigned employees.';

comment on column benew.app_user.created_at is 
    'Record creation timestamp with timezone. Managed by Spring Data JPA @CreatedDate annotation.';

comment on column benew.app_user.updated_at is 
    'Record last update timestamp with timezone. Managed by Spring Data JPA @LastModifiedDate annotation.';

--rollback drop table if exists benew.app_user cascade;

