--liquibase formatted sql

--changeset benew:20251103100003_create_onboarding_tables
--comment: Create onboarding_process and onboarding_task tables for tracking employee onboarding

/*
 * Migration: Create Onboarding Tables
 * Purpose: Create tables for tracking individual employee onboarding processes
 * Author: Database Architect
 * Date: 2025-11-03
 * 
 * This migration creates two tables:
 * 1. onboarding_process - represents one employee's onboarding journey
 * 2. onboarding_task - individual tasks copied from template_task for this process
 * 
 * Key Design Decisions:
 * - Process is automatically created when employee account is created
 * - Tasks are COPIED from template_task (not referenced), so template changes
 *   don't affect active processes (versioning via denormalization)
 * - Progress counters (total_tasks_count, completed_tasks_count) are denormalized
 *   for fast dashboard reads without expensive COUNT() queries
 * - status field supports ACTIVE and ARCHIVED states
 * - ON DELETE RESTRICT on all foreign keys forces application to handle deletions
 * 
 * Tables Created: 
 * - benew.onboarding_process
 * - benew.onboarding_task
 * 
 * Dependencies: 
 * - benew.app_user (from migration 20251103100001)
 * - benew.template (from migration 20251103100002)
 * 
 * Special Notes:
 * - Application is responsible for updating progress counters when tasks complete
 * - source_template_id is kept for audit purposes but not used for task lookup
 * - is_completed toggle triggers counter updates in application logic
 */

-- create onboarding_process table
-- represents one employee's onboarding journey from start to completion/archive
create table benew.onboarding_process (
    -- primary key: uuid generated by spring boot application
    id uuid primary key,
    
    -- foreign key to employee being onboarded
    -- one user can have multiple processes (e.g., if changing positions)
    user_id uuid not null,
    
    -- foreign key to manager overseeing this onboarding
    -- manager sees all their employees' processes on dashboard
    manager_id uuid not null,
    
    -- foreign key to template that was used to create this process
    -- kept for audit/reporting purposes only
    -- actual tasks are copied to onboarding_task table
    source_template_id uuid not null,
    
    -- process status: ACTIVE or ARCHIVED
    -- ACTIVE = currently ongoing
    -- ARCHIVED = completed and moved to archive by manager
    -- validated at application level via java enum
    status varchar(50) not null,
    
    -- denormalized progress counters for fast dashboard queries
    -- updated by application when tasks are marked complete/incomplete
    -- avoids expensive COUNT(*) queries on onboarding_task table
    total_tasks_count integer not null default 0,
    completed_tasks_count integer not null default 0,
    
    -- audit columns managed by spring data jpa auditing
    created_at timestamptz not null,
    updated_at timestamptz not null,
    
    -- foreign key to employee user
    -- on delete restrict prevents deletion of users with active onboarding
    -- application must complete/archive process before user deletion
    constraint fk_onboarding_process_user 
        foreign key (user_id) 
        references benew.app_user(id) 
        on delete restrict,
    
    -- foreign key to manager user
    -- on delete restrict prevents deletion of managers overseeing processes
    -- application must reassign processes before manager deletion
    constraint fk_onboarding_process_manager 
        foreign key (manager_id) 
        references benew.app_user(id) 
        on delete restrict,
    
    -- foreign key to source template
    -- on delete restrict prevents deletion of templates used in processes
    -- kept for audit trail even though tasks are copied
    constraint fk_onboarding_process_template 
        foreign key (source_template_id) 
        references benew.template(id) 
        on delete restrict
);

-- table comment
comment on table benew.onboarding_process is 
    'Represents one employee onboarding process. Automatically created when employee account is created. Tasks are copied from template_task to onboarding_task at creation time.';

-- column comments
comment on column benew.onboarding_process.id is 
    'Primary key (UUID). Generated by Spring Boot using @GeneratedValue(strategy = GenerationType.UUID).';

comment on column benew.onboarding_process.user_id is 
    'Foreign key to employee being onboarded (benew.app_user). ON DELETE RESTRICT.';

comment on column benew.onboarding_process.manager_id is 
    'Foreign key to manager overseeing onboarding (benew.app_user). ON DELETE RESTRICT.';

comment on column benew.onboarding_process.source_template_id is 
    'Foreign key to template used to create this process (benew.template). Kept for audit purposes. Actual tasks are copied to onboarding_task. ON DELETE RESTRICT.';

comment on column benew.onboarding_process.status is 
    'Process status: ACTIVE or ARCHIVED. ACTIVE = ongoing, ARCHIVED = completed and moved to archive. Validated in Spring application via @Enumerated(EnumType.STRING).';

comment on column benew.onboarding_process.total_tasks_count is 
    'Denormalized count of all tasks. Updated by application when tasks added. Enables fast progress calculation without COUNT() query.';

comment on column benew.onboarding_process.completed_tasks_count is 
    'Denormalized count of completed tasks. Updated by application when tasks marked done. Progress % = (completed_tasks_count / total_tasks_count) * 100.';

comment on column benew.onboarding_process.created_at is 
    'Record creation timestamp with timezone. Managed by Spring Data JPA @CreatedDate annotation.';

comment on column benew.onboarding_process.updated_at is 
    'Record last update timestamp with timezone. Managed by Spring Data JPA @LastModifiedDate annotation.';

-- create onboarding_task table
-- stores individual tasks for a specific onboarding process
-- tasks are COPIED from template_task when process is created
create table benew.onboarding_task (
    -- primary key: uuid generated by spring boot application
    id uuid primary key,
    
    -- foreign key to parent onboarding process
    -- one process can have many tasks
    onboarding_process_id uuid not null,
    
    -- task information (copied from template_task)
    -- these fields are snapshots at time of process creation
    -- changes to template tasks will NOT affect these values
    title varchar(255) not null,
    
    -- optional detailed instructions
    description text,
    
    -- display order in checklist
    task_order integer not null,
    
    -- who is responsible: MANAGER or USER
    owner_role varchar(50) not null,
    
    -- completion status
    -- toggled by task owner (manager or employee)
    -- triggers update of completed_tasks_count in onboarding_process
    is_completed boolean not null default false,
    
    -- audit columns managed by spring data jpa auditing
    created_at timestamptz not null,
    updated_at timestamptz not null,
    
    -- foreign key constraint to onboarding process
    -- on delete restrict prevents deletion of processes with tasks
    -- application must delete tasks first (or cascade would also be reasonable here)
    constraint fk_onboarding_task_process 
        foreign key (onboarding_process_id) 
        references benew.onboarding_process(id) 
        on delete restrict
);

-- table comment
comment on table benew.onboarding_task is 
    'Individual tasks for a specific onboarding process. Tasks are COPIED from template_task when process is created. Changes to template tasks do NOT affect these tasks (versioning via denormalization).';

-- column comments
comment on column benew.onboarding_task.id is 
    'Primary key (UUID). Generated by Spring Boot using @GeneratedValue(strategy = GenerationType.UUID).';

comment on column benew.onboarding_task.onboarding_process_id is 
    'Foreign key to onboarding_process. One process has many tasks. ON DELETE RESTRICT.';

comment on column benew.onboarding_task.title is 
    'Task title. Copied from template_task.title at process creation. Template changes do NOT update this value.';

comment on column benew.onboarding_task.description is 
    'Task description. Copied from template_task.description at process creation. Template changes do NOT update this value.';

comment on column benew.onboarding_task.task_order is 
    'Display order in checklist. Copied from template_task.task_order at process creation.';

comment on column benew.onboarding_task.owner_role is 
    'Role responsible for completing task: MANAGER or USER. Copied from template_task.owner_role at process creation. Validated in Spring application via @Enumerated(EnumType.STRING).';

comment on column benew.onboarding_task.is_completed is 
    'Task completion status. Set to true by task owner (manager or employee). Triggers update of completed_tasks_count in onboarding_process table.';

comment on column benew.onboarding_task.created_at is 
    'Record creation timestamp with timezone. Managed by Spring Data JPA @CreatedDate annotation.';

comment on column benew.onboarding_task.updated_at is 
    'Record last update timestamp with timezone. Managed by Spring Data JPA @LastModifiedDate annotation.';

--rollback drop table if exists benew.onboarding_task cascade;
--rollback drop table if exists benew.onboarding_process cascade;

