--liquibase formatted sql

--changeset benew:20251103100002_create_template_tables
--comment: Create template and template_task tables for onboarding checklist templates

/*
 * Migration: Create Template Tables
 * Purpose: Create tables for managing onboarding checklist templates
 * Author: Database Architect
 * Date: 2025-11-03
 * 
 * This migration creates two tables:
 * 1. template - header table for checklist templates (one per job position)
 * 2. template_task - tasks that belong to each template
 * 
 * Key Design Decisions:
 * - Templates are tied to job positions (position_name must be unique)
 * - Template versioning via denormalization: tasks are COPIED to onboarding_task
 *   when process is created, so changes to template don't affect active onboardings
 * - task_order controls display sequence in checklist
 * - owner_role (MANAGER or USER) determines who is responsible for completing task
 * - ON DELETE RESTRICT prevents deletion of templates/tasks if still referenced
 * 
 * Tables Created: 
 * - benew.template
 * - benew.template_task
 * 
 * Dependencies: benew schema (from migration 20251103100000)
 * 
 * Special Notes:
 * - position_name uniqueness enforced at database level
 * - Additional case-insensitive unique index on position_name in later migration
 * - CSV import feature will bulk insert template_task records
 */

-- create template table
-- header table for onboarding checklists, one per job position
create table benew.template (
    -- primary key: uuid generated by spring boot application
    id uuid primary key,
    
    -- unique job position name that this template applies to
    -- application normalizes this value (trim + toLowerCase) before save/search
    -- e.g., "Software Engineer", "Product Manager", etc.
    position_name varchar(50) not null,
    
    -- audit columns managed by spring data jpa auditing
    created_at timestamptz not null,
    updated_at timestamptz not null,
    
    -- unique constraint on position_name
    -- ensures only one template per job position
    -- case-insensitive uniqueness enforced via separate index in later migration
    constraint uk_template_position_name 
        unique (position_name)
);

-- table comment
comment on table benew.template is 
    'Header table for onboarding checklist templates. One template per job position. Tasks are defined in template_task table and copied to onboarding_task when process starts.';

-- column comments
comment on column benew.template.id is 
    'Primary key (UUID). Generated by Spring Boot using @GeneratedValue(strategy = GenerationType.UUID).';

comment on column benew.template.position_name is 
    'Unique job position name (e.g., "Software Engineer"). Application normalizes via trim().toLowerCase() before save/search. Case-insensitive uniqueness enforced via functional index.';

comment on column benew.template.created_at is 
    'Record creation timestamp with timezone. Managed by Spring Data JPA @CreatedDate annotation.';

comment on column benew.template.updated_at is 
    'Record last update timestamp with timezone. Managed by Spring Data JPA @LastModifiedDate annotation.';

-- create template_task table
-- stores individual tasks that make up a template checklist
create table benew.template_task (
    -- primary key: uuid generated by spring boot application
    id uuid primary key,
    
    -- foreign key to parent template
    -- one template can have many tasks
    template_id uuid not null,
    
    -- task information
    -- title is short description displayed in checklist
    title varchar(255) not null,
    
    -- description is optional detailed instructions for the task
    -- stored as text to allow longer content
    description text,
    
    -- display order for tasks in checklist
    -- lower numbers appear first
    -- allows administrators to reorder tasks
    task_order integer not null,
    
    -- who is responsible for completing this task
    -- values: MANAGER or USER
    -- validated at application level via java enum
    owner_role varchar(50) not null,
    
    -- audit columns managed by spring data jpa auditing
    created_at timestamptz not null,
    updated_at timestamptz not null,
    
    -- foreign key constraint to template
    -- on delete restrict prevents deletion of templates that still have tasks
    -- application must delete tasks first, then template
    constraint fk_template_task_template 
        foreign key (template_id) 
        references benew.template(id) 
        on delete restrict
);

-- table comment
comment on table benew.template_task is 
    'Individual tasks that make up a template checklist. When onboarding process is created, these tasks are COPIED to onboarding_task table. Changes to template tasks do NOT affect already active onboarding processes (versioning via denormalization).';

-- column comments
comment on column benew.template_task.id is 
    'Primary key (UUID). Generated by Spring Boot using @GeneratedValue(strategy = GenerationType.UUID).';

comment on column benew.template_task.template_id is 
    'Foreign key to template. One template has many tasks. ON DELETE RESTRICT.';

comment on column benew.template_task.title is 
    'Short task title displayed in checklist (max 255 chars). Required.';

comment on column benew.template_task.description is 
    'Optional detailed task description/instructions. Can be lengthy (TEXT type).';

comment on column benew.template_task.task_order is 
    'Display order in checklist. Lower numbers appear first. Allows task reordering by administrators.';

comment on column benew.template_task.owner_role is 
    'Role responsible for completing task: MANAGER or USER. Validated in Spring application via @Enumerated(EnumType.STRING).';

comment on column benew.template_task.created_at is 
    'Record creation timestamp with timezone. Managed by Spring Data JPA @CreatedDate annotation.';

comment on column benew.template_task.updated_at is 
    'Record last update timestamp with timezone. Managed by Spring Data JPA @LastModifiedDate annotation.';

--rollback drop table if exists benew.template_task cascade;
--rollback drop table if exists benew.template cascade;

