spring:
  application:
    name: benew
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: benew
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  swagger-ui:
    enabled: false
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}