package com.narciarz.benew.models;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity representing a system user in the app_user table.
 * 
 * <p>This is the central user table storing all users with three distinct roles:
 * ADMIN, MANAGER, and USER. Implements a self-referencing manager-employee hierarchy
 * via the managerId field.</p>
 * 
 * <p>Key design decisions:</p>
 * <ul>
 *   <li>UUID primary keys generated by application using {@code @GeneratedValue(strategy = GenerationType.UUID)}</li>
 *   <li>Email is used as username for authentication and must be unique (case-insensitive)</li>
 *   <li>Password is stored as BCrypt hash, never plain text</li>
 *   <li>Role validation at application level via {@code @Enumerated(EnumType.STRING)}</li>
 *   <li>Audit columns managed by Spring Data JPA Auditing (inherited from BaseEntity)</li>
 *   <li>Manager relationship uses ON DELETE RESTRICT to prevent deletion of managers with employees</li>
 * </ul>
 */
@Entity
@Table(name = "app_user", schema = "benew")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class AppUser extends BaseEntity {
    
    /**
     * User email address used as username for authentication.
     * Must be unique (case-insensitive check via database index).
     */
    @Column(name = "email", nullable = false, unique = true, length = 255)
    private String email;
    
    /**
     * BCrypt password hash. Never store plain text passwords.
     * Managed by Spring Security.
     */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;
    
    /**
     * User role: ADMIN, MANAGER, or USER.
     * Stored as VARCHAR in database, validated at application level.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 50)
    private UserRole role;
    
    /**
     * User first name. Required for all users.
     */
    @Column(name = "first_name", nullable = false, length = 50)
    private String firstName;
    
    /**
     * User last name. Required for all users. Indexed for search performance.
     */
    @Column(name = "last_name", nullable = false, length = 50)
    private String lastName;
    
    /**
     * Job title/position. Used to assign appropriate onboarding template
     * when creating new employee. NULL for administrators.
     * Application normalizes value (trim + toLowerCase) before save/search.
     */
    @Column(name = "position_name", length = 50)
    private String positionName;
    
    /**
     * Self-referencing foreign key to manager (another user in this table).
     * NULL for administrators and top-level managers without supervisors.
     * ON DELETE RESTRICT prevents deletion of managers with assigned employees.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "manager_id", foreignKey = @ForeignKey(name = "fk_app_user_manager"))
    private AppUser manager;
}


