package com.narciarz.benew.models;

import jakarta.persistence.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Entity representing a system user in the app_user table.
 * 
 * <p>This is the central user table storing all users with three distinct roles:
 * ADMIN, MANAGER, and USER. Implements a self-referencing manager-employee hierarchy
 * via the managerId field.</p>
 * 
 * <p>Key design decisions:</p>
 * <ul>
 *   <li>UUID primary keys generated by application using {@code @GeneratedValue(strategy = GenerationType.UUID)}</li>
 *   <li>Email is used as username for authentication and must be unique (case-insensitive)</li>
 *   <li>Password is stored as BCrypt hash, never plain text</li>
 *   <li>Role validation at application level via {@code @Enumerated(EnumType.STRING)}</li>
 *   <li>Audit columns managed by Spring Data JPA Auditing</li>
 *   <li>Manager relationship uses ON DELETE RESTRICT to prevent deletion of managers with employees</li>
 * </ul>
 */
@Entity
@Table(name = "app_user", schema = "benew")
@EntityListeners(AuditingEntityListener.class)
public class AppUser {
    
    /**
     * Primary key (UUID). Generated by Spring Boot using UUID strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;
    
    /**
     * User email address used as username for authentication.
     * Must be unique (case-insensitive check via database index).
     */
    @Column(name = "email", nullable = false, unique = true, length = 255)
    private String email;
    
    /**
     * BCrypt password hash. Never store plain text passwords.
     * Managed by Spring Security.
     */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;
    
    /**
     * User role: ADMIN, MANAGER, or USER.
     * Stored as VARCHAR in database, validated at application level.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 50)
    private UserRole role;
    
    /**
     * User first name. Required for all users.
     */
    @Column(name = "first_name", nullable = false, length = 50)
    private String firstName;
    
    /**
     * User last name. Required for all users. Indexed for search performance.
     */
    @Column(name = "last_name", nullable = false, length = 50)
    private String lastName;
    
    /**
     * Job title/position. Used to assign appropriate onboarding template
     * when creating new employee. NULL for administrators.
     * Application normalizes value (trim + toLowerCase) before save/search.
     */
    @Column(name = "position_name", length = 50)
    private String positionName;
    
    /**
     * Self-referencing foreign key to manager (another user in this table).
     * NULL for administrators and top-level managers without supervisors.
     * ON DELETE RESTRICT prevents deletion of managers with assigned employees.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "manager_id", foreignKey = @ForeignKey(name = "fk_app_user_manager"))
    private AppUser manager;
    
    /**
     * Record creation timestamp with timezone.
     * Managed by Spring Data JPA @CreatedDate annotation.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;
    
    /**
     * Record last update timestamp with timezone.
     * Managed by Spring Data JPA @LastModifiedDate annotation.
     */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    // Constructors
    public AppUser() {
    }

    public AppUser(String email, String passwordHash, UserRole role, String firstName, 
                   String lastName, String positionName, AppUser manager) {
        this.email = email;
        this.passwordHash = passwordHash;
        this.role = role;
        this.firstName = firstName;
        this.lastName = lastName;
        this.positionName = positionName;
        this.manager = manager;
    }

    // Getters and Setters
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public UserRole getRole() {
        return role;
    }

    public void setRole(UserRole role) {
        this.role = role;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPositionName() {
        return positionName;
    }

    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    public AppUser getManager() {
        return manager;
    }

    public void setManager(AppUser manager) {
        this.manager = manager;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}

