package com.narciarz.benew.models;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Base entity class for all JPA entities in the application.
 * 
 * <p>Provides common fields that are shared across all entities:</p>
 * <ul>
 *   <li>id - UUID primary key, generated automatically</li>
 *   <li>createdAt - timestamp when the entity was created (managed by JPA Auditing)</li>
 *   <li>updatedAt - timestamp when the entity was last updated (managed by JPA Auditing)</li>
 * </ul>
 * 
 * <p>All entities should extend this class to inherit these common fields
 * and avoid code duplication. JPA Auditing is enabled via {@code @EntityListeners}
 * annotation to automatically manage timestamps.</p>
 */
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
public abstract class BaseEntity {
    
    /**
     * Primary key (UUID). Generated by Spring Boot using UUID strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;
    
    /**
     * Record creation timestamp with timezone.
     * Managed by Spring Data JPA @CreatedDate annotation.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;
    
    /**
     * Record last update timestamp with timezone.
     * Managed by Spring Data JPA @LastModifiedDate annotation.
     */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;
}
