package com.narciarz.benew.models;

import jakarta.persistence.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Entity representing a task within an onboarding process in the onboarding_task table.
 * 
 * <p>Individual tasks for a specific onboarding process. Tasks are COPIED from template_task
 * when process is created. Changes to template tasks do NOT affect these tasks
 * (versioning via denormalization).</p>
 * 
 * <p>Key design decisions:</p>
 * <ul>
 *   <li>Tasks are copied from template_task (snapshots at time of process creation)</li>
 *   <li>Template changes will NOT affect these values</li>
 *   <li>isCompleted toggle triggers counter updates in onboarding_process</li>
 *   <li>ON DELETE RESTRICT prevents deletion of processes with tasks</li>
 * </ul>
 */
@Entity
@Table(name = "onboarding_task", schema = "benew")
@EntityListeners(AuditingEntityListener.class)
public class OnboardingTask {
    
    /**
     * Primary key (UUID). Generated by Spring Boot using UUID strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;
    
    /**
     * Foreign key to parent onboarding process. One process has many tasks.
     * ON DELETE RESTRICT prevents deletion of processes with tasks.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "onboarding_process_id", nullable = false, foreignKey = @ForeignKey(name = "fk_onboarding_task_process"))
    private OnboardingProcess onboardingProcess;
    
    /**
     * Task title. Copied from template_task.title at process creation.
     * Template changes do NOT update this value.
     */
    @Column(name = "title", nullable = false, length = 255)
    private String title;
    
    /**
     * Task description. Copied from template_task.description at process creation.
     * Template changes do NOT update this value.
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
    
    /**
     * Display order in checklist. Copied from template_task.task_order at process creation.
     */
    @Column(name = "task_order", nullable = false)
    private Integer taskOrder;
    
    /**
     * Role responsible for completing task: MANAGER or USER.
     * Copied from template_task.owner_role at process creation.
     * Stored as VARCHAR in database, validated at application level.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "owner_role", nullable = false, length = 50)
    private TaskOwnerRole ownerRole;
    
    /**
     * Task completion status. Set to true by task owner (manager or employee).
     * Triggers update of completed_tasks_count in onboarding_process table.
     */
    @Column(name = "is_completed", nullable = false)
    private Boolean isCompleted = false;
    
    /**
     * Record creation timestamp with timezone.
     * Managed by Spring Data JPA @CreatedDate annotation.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;
    
    /**
     * Record last update timestamp with timezone.
     * Managed by Spring Data JPA @LastModifiedDate annotation.
     */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    // Constructors
    public OnboardingTask() {
    }

    public OnboardingTask(OnboardingProcess onboardingProcess, String title, String description,
                         Integer taskOrder, TaskOwnerRole ownerRole) {
        this.onboardingProcess = onboardingProcess;
        this.title = title;
        this.description = description;
        this.taskOrder = taskOrder;
        this.ownerRole = ownerRole;
        this.isCompleted = false;
    }

    // Getters and Setters
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public OnboardingProcess getOnboardingProcess() {
        return onboardingProcess;
    }

    public void setOnboardingProcess(OnboardingProcess onboardingProcess) {
        this.onboardingProcess = onboardingProcess;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getTaskOrder() {
        return taskOrder;
    }

    public void setTaskOrder(Integer taskOrder) {
        this.taskOrder = taskOrder;
    }

    public TaskOwnerRole getOwnerRole() {
        return ownerRole;
    }

    public void setOwnerRole(TaskOwnerRole ownerRole) {
        this.ownerRole = ownerRole;
    }

    public Boolean getIsCompleted() {
        return isCompleted;
    }

    public void setIsCompleted(Boolean isCompleted) {
        this.isCompleted = isCompleted;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}


