package com.narciarz.benew.models;

import jakarta.persistence.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Entity representing an employee onboarding process in the onboarding_process table.
 * 
 * <p>Represents one employee's onboarding journey from start to completion/archive.
 * Automatically created when employee account is created. Tasks are copied from
 * template_task to onboarding_task at creation time.</p>
 * 
 * <p>Key design decisions:</p>
 * <ul>
 *   <li>Process is automatically created when employee account is created</li>
 *   <li>Tasks are COPIED from template_task (not referenced), so template changes
 *       don't affect active processes (versioning via denormalization)</li>
 *   <li>Progress counters (totalTasksCount, completedTasksCount) are denormalized
 *       for fast dashboard reads without expensive COUNT() queries</li>
 *   <li>status field supports ACTIVE and ARCHIVED states</li>
 *   <li>ON DELETE RESTRICT on all foreign keys forces application to handle deletions</li>
 * </ul>
 */
@Entity
@Table(name = "onboarding_process", schema = "benew")
@EntityListeners(AuditingEntityListener.class)
public class OnboardingProcess {
    
    /**
     * Primary key (UUID). Generated by Spring Boot using UUID strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;
    
    /**
     * Foreign key to employee being onboarded (benew.app_user).
     * One user can have multiple processes (e.g., if changing positions).
     * ON DELETE RESTRICT prevents deletion of users with active onboarding.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false, foreignKey = @ForeignKey(name = "fk_onboarding_process_user"))
    private AppUser user;
    
    /**
     * Foreign key to manager overseeing this onboarding (benew.app_user).
     * Manager sees all their employees' processes on dashboard.
     * ON DELETE RESTRICT prevents deletion of managers overseeing processes.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "manager_id", nullable = false, foreignKey = @ForeignKey(name = "fk_onboarding_process_manager"))
    private AppUser manager;
    
    /**
     * Foreign key to template used to create this process (benew.template).
     * Kept for audit/reporting purposes only. Actual tasks are copied to onboarding_task.
     * ON DELETE RESTRICT prevents deletion of templates used in processes.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "source_template_id", nullable = false, foreignKey = @ForeignKey(name = "fk_onboarding_process_template"))
    private Template sourceTemplate;
    
    /**
     * Process status: ACTIVE or ARCHIVED.
     * ACTIVE = currently ongoing, ARCHIVED = completed and moved to archive.
     * Stored as VARCHAR in database, validated at application level.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 50)
    private OnboardingStatus status;
    
    /**
     * Denormalized count of all tasks. Updated by application when tasks added.
     * Enables fast progress calculation without COUNT() query.
     */
    @Column(name = "total_tasks_count", nullable = false)
    private Integer totalTasksCount = 0;
    
    /**
     * Denormalized count of completed tasks. Updated by application when tasks marked done.
     * Progress % = (completedTasksCount / totalTasksCount) * 100.
     */
    @Column(name = "completed_tasks_count", nullable = false)
    private Integer completedTasksCount = 0;
    
    /**
     * Record creation timestamp with timezone.
     * Managed by Spring Data JPA @CreatedDate annotation.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;
    
    /**
     * Record last update timestamp with timezone.
     * Managed by Spring Data JPA @LastModifiedDate annotation.
     */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    // Constructors
    public OnboardingProcess() {
    }

    public OnboardingProcess(AppUser user, AppUser manager, Template sourceTemplate, 
                            OnboardingStatus status) {
        this.user = user;
        this.manager = manager;
        this.sourceTemplate = sourceTemplate;
        this.status = status;
        this.totalTasksCount = 0;
        this.completedTasksCount = 0;
    }

    // Getters and Setters
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public AppUser getUser() {
        return user;
    }

    public void setUser(AppUser user) {
        this.user = user;
    }

    public AppUser getManager() {
        return manager;
    }

    public void setManager(AppUser manager) {
        this.manager = manager;
    }

    public Template getSourceTemplate() {
        return sourceTemplate;
    }

    public void setSourceTemplate(Template sourceTemplate) {
        this.sourceTemplate = sourceTemplate;
    }

    public OnboardingStatus getStatus() {
        return status;
    }

    public void setStatus(OnboardingStatus status) {
        this.status = status;
    }

    public Integer getTotalTasksCount() {
        return totalTasksCount;
    }

    public void setTotalTasksCount(Integer totalTasksCount) {
        this.totalTasksCount = totalTasksCount;
    }

    public Integer getCompletedTasksCount() {
        return completedTasksCount;
    }

    public void setCompletedTasksCount(Integer completedTasksCount) {
        this.completedTasksCount = completedTasksCount;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}


