package com.narciarz.benew.models;

import jakarta.persistence.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Entity representing an onboarding checklist template in the template table.
 * 
 * <p>Header table for onboarding checklists, one per job position. Tasks are defined
 * in the TemplateTask entity and copied to OnboardingTask when a process starts.</p>
 * 
 * <p>Key design decisions:</p>
 * <ul>
 *   <li>Templates are tied to job positions (positionName must be unique)</li>
 *   <li>Template versioning via denormalization: tasks are COPIED to onboarding_task
 *       when process is created, so changes to template don't affect active onboardings</li>
 *   <li>Application normalizes positionName (trim + toLowerCase) before save/search</li>
 *   <li>Case-insensitive uniqueness enforced via database functional index</li>
 * </ul>
 */
@Entity
@Table(name = "template", schema = "benew")
@EntityListeners(AuditingEntityListener.class)
public class Template {
    
    /**
     * Primary key (UUID). Generated by Spring Boot using UUID strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;
    
    /**
     * Unique job position name that this template applies to (e.g., "Software Engineer").
     * Application normalizes this value (trim + toLowerCase) before save/search.
     * Case-insensitive uniqueness enforced via functional index.
     */
    @Column(name = "position_name", nullable = false, unique = true, length = 50)
    private String positionName;
    
    /**
     * Record creation timestamp with timezone.
     * Managed by Spring Data JPA @CreatedDate annotation.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;
    
    /**
     * Record last update timestamp with timezone.
     * Managed by Spring Data JPA @LastModifiedDate annotation.
     */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    // Constructors
    public Template() {
    }

    public Template(String positionName) {
        this.positionName = positionName;
    }

    // Getters and Setters
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getPositionName() {
        return positionName;
    }

    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}

