package com.narciarz.benew.models;

import jakarta.persistence.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Entity representing a task within a template checklist in the template_task table.
 * 
 * <p>Individual tasks that make up a template checklist. When an onboarding process
 * is created, these tasks are COPIED to the onboarding_task table. Changes to template
 * tasks do NOT affect already active onboarding processes (versioning via denormalization).</p>
 * 
 * <p>Key design decisions:</p>
 * <ul>
 *   <li>Tasks belong to a parent template (one template can have many tasks)</li>
 *   <li>task_order controls display sequence in checklist</li>
 *   <li>owner_role (MANAGER or USER) determines who is responsible for completing task</li>
 *   <li>ON DELETE RESTRICT prevents deletion of templates that still have tasks</li>
 * </ul>
 */
@Entity
@Table(name = "template_task", schema = "benew")
@EntityListeners(AuditingEntityListener.class)
public class TemplateTask {
    
    /**
     * Primary key (UUID). Generated by Spring Boot using UUID strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;
    
    /**
     * Foreign key to parent template. One template has many tasks.
     * ON DELETE RESTRICT prevents deletion of templates with tasks.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "template_id", nullable = false, foreignKey = @ForeignKey(name = "fk_template_task_template"))
    private Template template;
    
    /**
     * Short task title displayed in checklist (max 255 chars). Required.
     */
    @Column(name = "title", nullable = false, length = 255)
    private String title;
    
    /**
     * Optional detailed task description/instructions. Can be lengthy (TEXT type).
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
    
    /**
     * Display order in checklist. Lower numbers appear first.
     * Allows task reordering by administrators.
     */
    @Column(name = "task_order", nullable = false)
    private Integer taskOrder;
    
    /**
     * Role responsible for completing task: MANAGER or USER.
     * Stored as VARCHAR in database, validated at application level.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "owner_role", nullable = false, length = 50)
    private TaskOwnerRole ownerRole;
    
    /**
     * Record creation timestamp with timezone.
     * Managed by Spring Data JPA @CreatedDate annotation.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;
    
    /**
     * Record last update timestamp with timezone.
     * Managed by Spring Data JPA @LastModifiedDate annotation.
     */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    // Constructors
    public TemplateTask() {
    }

    public TemplateTask(Template template, String title, String description, 
                       Integer taskOrder, TaskOwnerRole ownerRole) {
        this.template = template;
        this.title = title;
        this.description = description;
        this.taskOrder = taskOrder;
        this.ownerRole = ownerRole;
    }

    // Getters and Setters
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public Template getTemplate() {
        return template;
    }

    public void setTemplate(Template template) {
        this.template = template;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getTaskOrder() {
        return taskOrder;
    }

    public void setTaskOrder(Integer taskOrder) {
        this.taskOrder = taskOrder;
    }

    public TaskOwnerRole getOwnerRole() {
        return ownerRole;
    }

    public void setOwnerRole(TaskOwnerRole ownerRole) {
        this.ownerRole = ownerRole;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}


